### ISSUE TITLE
Remove edition buttons if the user is not allowed to edit an entity (GS or SAT)

### ISSUE THREAD

**Issue by agmuino** [satnet-project/satnet-ng#18]
If the user is not allowed to edit the configuration/channels/availability of a GS or a satellite it is better to hide the edition buttons in the web.

I am assuming that the permissions for edition of each user is checked in the server side.

**Comment by rtubio** [comment]
The version that I am testing right now for the server checks this issue; unfortunately, I have not installed it yet in the server. Once I install it and I fix this issue in the interface, I will give an update here on this thread.

**Comment by rtubio** [comment]
I have just implemented this functionality and, from now on, it should not be possible to edit either the SC or GS that does not belong to the user that is operating the system.

Another thing that has to be done is to mark the TLE's as "used" right after somebody assigns them to a given spacecraft, so that nobody else can use them later.
